### ISSUE TITLE
Not turrning off Monitor, only blanking screen

### ISSUE THREAD

**Issue by spospordo** [bugsounet/MMM-Pir#11]
I noticed this module was only turning on ecomode, but not turning off the display.  The eventual solution was changing the dtoverlay settings in the boot config below. I'm not sure if this is something that needs to be addressed. 

I'm running a Raspberry Pi 2b on raspberry pi os (bullseye v11)

1. sudo nano /boot/config.txt or any other editor
2. Change dtoverlay=vc4-kms-v3d to dtoverlay=vc4-fkms-v3d
3. reboot

https://github.com/raspberrypi/firmware/issues/1224#issuecomment-1470791044

**Comment by bugsounet** [comment]
Hi,

It's exactly that [Readme](https://github.com/bugsounet/MMM-Pir#notes) says ;)

Happy use,
@bugsounet
