### ISSUE TITLE
labwc: wlr-randr turn on/off comment will end up in un-fullscreening the magicmirror window 

### ISSUE THREAD

**Issue by Knapoc** [bugsounet/MMM-Pir#112]
According to a [labwc configuration file](https://github.com/labwc/labwc/blob/master/docs/autostart) one should not turn off displays by 'disabling outputs'. This is the case since the following commit: https://github.com/labwc/labwc/commit/a837fef
```
There is some positioning glitch still with un-fullscreening a window
whose output has been disconnected/disabled; it can end up in an
unexpected position (but at least has the correct size and decoration).
I don't think this is due to a bug in my change per se, but perhaps the
change has exposed a bug elsewhere.
```

From my personal observation, using `wlr-randr` to turn off the display ends up in a strange layout, where suddenly the menubar is present on the screen. Turning the display off and on using wlopm does not have this affect. wlrandr still needs to be used for use cases such as screen rotation etc.

Further information:

- Raspberry Pi OS Debian GNU/Linux 12 (bookworm) 
- Wayland compositor: labwc 0.7.2
- MMM-Pir: v2.0.0

**Comment by bugsounet** [comment]
Hi,
Sure i have to work around this. Labwc is New for rpi

I have to install it intro my test rpi dev or make a PR

**Comment by bugsounet** [comment]
Hi, just start to code it in #117
It will come soon with v2.2.0

**Comment by bugsounet** [comment]
v2.2.0 is out and now available with `display.mode:7`
