### ISSUE TITLE
MMM-GA v8 - Lost ability to wake screen with webcam

### ISSUE THREAD

**Issue by Gdenis3** [bugsounet/MMM-Pir#113]
With this new version of MMM-GoogleAssistant it's no more possible to use webcam to wake up the screen (only touch or PIR)
Is there another way to wake up screen with webcam ?

**Comment by bugsounet** [comment]
Hi,

I will add the library for making this job

**Comment by Gdenis3** [comment]
Merci beaucoup you're the best :)

**Comment by bugsounet** [comment]
Under Coding #114 and will comes with v2.1.0

**Comment by bugsounet** [comment]
This Feature is now coded in v2.1.0
in [Motion](https://github.com/bugsounet/MMM-Pir?tab=readme-ov-file#motion-configuration) feature
