### ISSUE TITLE
Pir Erorr EBUSY and screen error detected

### ISSUE THREAD

**Issue by Bursucel** [bugsounet/MMM-Pir#125]
Regardless of the mode I select for screen i get these two messages :
Pir Error detected: EBUSY,Device or resource busy
Screen error detected: dpms command error (mode:1). Changed the mode,still no joy.

I would appreciate any help you could provide.

**Comment by bugsounet** [comment]
Hi,

> Pir Error detected: EBUSY,Device or resource busy

it's seams that another process in your pi is already using your GPIO

> Screen error detected: dpms command error (mode:1)

what compositor do you use on your pi ?

**Comment by Bursucel** [comment]
Thank you for your reply. I had a small LCD connected on the other SPI bus,i think that was the issue.
Since I've disconnected it everything seems to work fine.
Thanks again for your work and the developing of this module. I appreciate it.


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
