### ISSUE TITLE
Old Pir worked, upgrade no working.

### ISSUE THREAD

**Issue by KimORichter** [bugsounet/MMM-Pir#126]
Problem:  MMM-Pir no longer works for me after upgrade.

my MMM-Pir was working just fine.  The monitor turned off / on by the counter perfectly.  I had LED lights that 
fadded up / down on cue with the monitor.  I was using mode 6 and monitor.py.

After upgrading, none of that is working any more.

I used the default Personalized Configuration, changing the following settings:

I have shut down and restarted the RPI4 many times with the same results.

With no changes other than config: mode, and GPIO: mode being changed here are my results:

---------------------

For Pir Configuration i have tried the following modes along with results:
    Pir: {
      mode: 0,
      gpio: 16
    },

mode 0: Pir Error detected: EBUSY, Device or resource busy
mode 1: Pir Error detected: Error: 'GPIO busy'
mode 2: Pir Error detected: EBUSY, Device or resource busy

---------------------

  config: {
		mode: 1,
		Pir: {
			mode: 0,
			gpio: 16		// verified correct pin
		}
    },

    Available mode / Results:
        mode: 0 - disabled mode
					Monitor: On -> Off -> Stays Off until mouse click,   LED Lights: OFF Always, Error: Pir Error detected: Error: 'GPIO busy'
        mode: 1 - use dpms (For raspbian 10/11 or raspbian 12 with x11 compositor)		
					Monitor: On -> Off -> Stays Off until mouse click,   LED Lights: OFF Always, Error: Screen Error detected: dpms command error (mode: 1), Pir Error detected: Error: 'GPIO busy'
        mode: 2 - use xrandr (For raspbian 11 or raspbian 12 with x11 compositor)       
					Monitor: On -> Off -> Stays Off until mouse click,   LED Lights: OFF Always, Error: Screen Error detected: dpms command error (mode: 2), Pir Error detected: Error: 'GPIO busy'
        mode: 3 - use wlr-randr (For raspbian 12 with wayfire compositor)
					Monitor: On -> Off -> Stays Off until mouse click,   LED Lights: OFF Always, Error: Screen Error detected: wlrandr command error (mode: 3), Pir Error detected: Error: 'GPIO busy'
        mode: 4 - use HDMI CEC
					Monitor: On -> Off -> Stays Off until mouse click,   LED Lights: OFF Always, Error: Pir Error detected: Error: 'GPIO busy'
        mode: 5 - use ddcutil (not yet documented)
					Monitor: On -> Off -> Stays Off until mouse click then reboots monitor,   LED Lights: OFF Always, Error: Pir Error detected: Error: 'GPIO busy'
        mode: 6 - use dpms (linux version for debian, ubuntu, ...)
					Monitor: On -> Off -> Stays Off until mouse click,   LED Lights: OFF Always, Error: Screen Error detected: dpms linux command error (mode: 6), Pir Error detected: Error: 'GPIO busy'
        mode: 7 - use labwc (For raspbian 12 with labwc compositor)
					Monitor: On -> Off -> Stays Off until mouse click,   LED Lights: OFF Always, Error: Screen Error detected: wlopm command error (mode: 7), Pir Error detected: Error: 'GPIO busy'

I believe the Pir error is the cause for the Monitor not performing power up except when clicked.

Which mode is the equivalent to old mode 6 (using monitor.py)?

I'm not extremely well versed in python programming and am struggling to understand the new code, but I would like to get MMM-Pir working again.

Any help would be appreciated.

Thank you.

Kim

**Comment by bugsounet** [comment]
Hi,

`Pir: {}` config block is reserved for pir sensor
If you don't have it, ReadMe says: `⚠ You can disable PIR Sensor detection by using gpio: 0`

v1.x `mode: 6` functionality is now recoded in `Display: {}` config block and ReadMe says: 
 * `mode: 8 - use pinctrl for switching a relay`
 * `relayGPIOPin`	- mode 8 only- GPIO pin of the relay

Let's read again [ReadMe](https://github.com/bugsounet/MMM-Pir?tab=readme-ov-file#configuration) for more details

**Comment by KimORichter** [comment]
Sorry, not sure why but I did not see readme up to mode 8.  I do now but not before.   

Pir is now working using mode 0.  

I switched to mode 8 and monitor turns off / on with Pir, however I do not know where to put my monitor.py code for the LED lights. 

Thanks for your help.

Kim

**Comment by bugsounet** [comment]
just report `mode6_gpio` value from v1.x to `relayGPIOPin` of v2

**Comment by KimORichter** [comment]
I don't think my last request was understood.

In v1.x I modified monitor.py code to turn LED lights on / off.  

I am asking where I put that code in v2.x.  I would like to know what file to add the code to turn the LEDs on / off.

Thank you.

**Comment by bugsounet** [comment]
MMM-Pir is not ready for control LED

I think the led controls are out of my module specification.

Maybe another module could handle this (see 3rd party module list)
For example, by reading the outgoing notifications from MMM-Pir about the state of your screen (MMM_PIR-SCREEN_POWERSTATUS), you can run your own custom python script with [MMM-NotificationTrigger](https://github.com/MMRIZE/MMM-NotificationTrigger)

**Comment by KimORichter** [comment]
Thanks, I will pursue that path.
