### ISSUE TITLE
Cron is DISABLED when not specifying a mode

### ISSUE THREAD

**Issue by SimoneMSR** [bugsounet/MMM-Pir#142]
Following the examples for CRON in `config.js` I get 

```
[2024-12-31 09:58:27.855] [LOG] [MMM-Pir] [LIB] [CRON] [MODE] Disabled
```

from console, and the cron does not seem to be executed. Please, can you document how to properly setup a cron. What are cron mode 0,1 and 2?

**Comment by bugsounet** [comment]
Hi, yes you have right !
I forget to make documentation about mode in CRON config :/
So it's will be disabled all time (mode: 0)

**Comment by bugsounet** [comment]
ReadMe is now updated with [v2.4.2](https://github.com/bugsounet/MMM-Pir/pull/134 )
