### ISSUE TITLE
Issue with monitor turning off but not back on.

### ISSUE THREAD

**Issue by ChrisRG711** [bugsounet/MMM-Pir#21]
I have a brand new Rasberry pi 4. 
Latest PI os
a HC-SR501 PIR Motion Sensor Module
here is my config. I have tried a few different modes. This one reflects the latest. They have all turned the screen off but none back on. I am new to this so not sure what i can do 

{
  module: 'MMM-Pir',
  position: 'top_left',
  config: {
    debug: false,
    delay: 2 * 60 * 1000,
    turnOffDisplay: true,
    mode: 9,
    ecoMode: true,
    displayCounter: true,
    displayBar: true,
    displayStyle: "Text",
    displayLastPresence: true,
    lastPresenceTimeFormat: "LL H:mm",
	mode6_gpio: 20,
    mode6_clearGpioValue: true,
	pir_gpio: 4,
    pir_reverseValue: false,
    xrandrForceRotation: "normal",
    wrandrForceRotation: "normal"
  }
},

**Comment by sdetweil** [comment]
I this is is pi4 and 64 bit then you have Wayland, so mode 10, right?  it is changed from last os

**Comment by bugsounet** [comment]
No response from @ChrisRG711 
Reopen this issue if needed
