### ISSUE TITLE
Can not get monitor to come back on

### ISSUE THREAD

**Issue by Buzzlig** [bugsounet/MMM-Pir#22]
I got the module install okay but can not get the screen to come back on. I am new to this stuff and have never setup a PIR on a PI 4 , maybe I don't have the PIR hooked up right to the PI right. I have search the internet on how to hook up the PIR directly to a PI 4 but found nothing. Below is what I have in the config.js file. I am running 64 bit desktop OS
 {
                        module: 'MMM-Pir',
                        position: 'top_left',
                        config: {
                          debug: false,
                          delay: 2 * 60 * 1000,
                          turnOffDisplay: true,
                          mode: 10,
                          ecoMode: true,
                          displayCounter: true,
                          displayBar: true,
                          displayStyle: "Text",
                          displayLastPresence: true,
                          lastPresenceTimeFormat: "LL H:mm",
                          mode6_gpio: 20,
                          mode6_clearGpioValue: true,
                          pir_gpio: 21,
                          pir_reverseValue: false
                }
                },

**Comment by sdetweil** [comment]
use a project in python to verify that the PIR os working correctly outside MM.

see https://projects.raspberrypi.org/en/projects/physical-computing/11

**Comment by Buzzlig** [comment]
Thank you I will try that.

**Comment by Buzzlig** [comment]
sedtweil, the PIR was bad ( good call ) I have just got a new PIR and tested it out on python and it works, but I still have the same issue where the screen goes blank but will not come back on. I have tried different modes ( 1 though 10 ) and none of them work. Then I tested the new PIR out on Python and it still works.
What else could I do that might fix this problem?
Thank you for your time.

**Comment by sdetweil** [comment]
@Buzzlig I cannot help with the module operations.. 
```
mode6_gpio: 20,
mode6_clearGpioValue: true,
pir_gpio: 21,
pir_reverseValue: false
```

do those match the gpio values used by python?

**Comment by Buzzlig** [comment]
I do not know where to find the gpio values by python.

**Comment by Buzzlig** [comment]
sdetweil, I figure out what you was asking me and I corrected Gpio numbers and it works.
Thank you again so much for your time. I hope the rest of your day goes great!
