### ISSUE TITLE
failed npm install - raspberry pi 2B

### ISSUE THREAD

**Issue by lshvarzberg** [bugsounet/MMM-Pir#50]
I've got error during npm-install:

22 timing reify Completed in 14359ms
123 timing command:install Completed in 14774ms
124 verbose stack Error: command failed
124 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
124 verbose stack     at ChildProcess.emit (node:events:519:28)
124 verbose stack     at maybeClose (node:internal/child_process:1105:16)
124 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
125 verbose pkgid MMM-Pir@1.5.0
126 verbose cwd /home/leonid/MagicMirror/modules/MMM-Pir
127 verbose Linux 6.1.21-v7+
128 verbose node v21.7.1
129 verbose npm  v10.5.0
130 error code 255
131 error path /home/leonid/MagicMirror/modules/MMM-Pir
132 error command failed
133 error command sh -c installer/preinstall.sh -d 'unclutter cec-utils ddcutil python3 python-is-python3 python3-gpiozero'
134 verbose exit 255
135 timing npm Completed in 18276ms
136 verbose code 255

**Comment by lshvarzberg** [comment]
Here is console message:
eonid@magicmirror:~/MagicMirror/modules/MMM-Pir $ npm install

> MMM-Pir@1.5.0 preinstall
> installer/preinstall.sh -d 'unclutter cec-utils ddcutil python3 python-is-python3 python3-gpiozero'


Welcome to MMM-Pir v1.5.0

No root checking...
Checking MMM-Pir: leonid/leonid
Checking MagicMirror: leonid/root
npm ERR! code 255
npm ERR! path /home/leonid/MagicMirror/modules/MMM-Pir
npm ERR! command failed
npm ERR! command sh -c installer/preinstall.sh -d 'unclutter cec-utils ddcutil python3 python-is-python3 python3-gpiozero'

npm ERR! A complete log of this run can be found in: /home/leonid/.npm/_logs/2024-03-20T23_15_23_495Z-debug-0.log

**Comment by bugsounet** [comment]
Hi, Installer check that MagicMirror Folder have `root` group property.
change it to your own group (`leonid`) and retry `MMM-Pir` install
