### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by juitoo** [bugsounet/MMM-Pir#66]
Good morning,
thanks for the module

I just did a complete reset of my RPi 4 and MM today and when installing the module I got this error message.

Can you help me ?

Thank you so much

![Nouvelle image bitmap](https://github.com/bugsounet/MMM-Pir/assets/168969873/6f5e02c5-011f-4169-b9e6-bdeba1a6b224)

**Comment by bugsounet** [comment]
Hi,

It's just because MagicMirror is on `root` group (really not logical)
it's must be, in your case, in `MM` group

try this command to correct:

```sh
cd ~
sudo chgrp -R MM MagicMirror
```

and retry to install `MMM-Pir`

**Comment by juitoo** [comment]
Merci ! l'installation c'est beaucoup mieux passé, cependant lors du lancement de MM  :
![Nouvelle image bitmap](https://github.com/bugsounet/MMM-Pir/assets/168969873/30bfadea-a4fb-4150-aab4-28bc1656e59e)


Ps: je viens de voir que a fait un module pour Netatmo ! tu viens de faire ma journée ! merci beaucoup !

**Comment by bugsounet** [comment]
![image](https://github.com/bugsounet/MMM-Pir/assets/30669209/4f8f5568-1893-4fbb-8396-ac3f5a843e80)

Vous avez configuré `pir_mode: 6,` donc la valeur n'est pas reconnu (valeur possible: `0`, `1`, `2`)

**Comment by juitoo** [comment]
Merci, oui j'ai confondu avec "mode". Erreur bete

Merci pour votre aide. Je débute, je n'ai pas beaucoup d'expérience sur MM ou sur Linux.

Je viens de tout modifier et a présent le module détecte une présence toute le 1s (j'ai mi la veille a 10s pour les teste) alors que le PIR est caché dans le noir.

![Nouvelle image bitmap](https://github.com/bugsounet/MMM-Pir/assets/168969873/40e976b5-9cdd-4aed-9ecd-9b3a99655d39)

**Comment by juitoo** [comment]
problème de capteur résolut en en mettant un nouveau.
