### ISSUE TITLE
Adding a backlight off command (since screen wont turn off)

### ISSUE THREAD

**Issue by anthonymgil** [bugsounet/MMM-Pir#71]
First, wanna say thanks for all your work on this. Was really simple to set up and get working.  The timer "shuts down" the screen and turns it back on during an approach. The issue that I am having is that the backlight stays on. I am pretty sure that this is the monitor turning back on for some reason as it will flash off for a second then turn back on to a black screen with the backlight turned on.   This is what I am trying to fix.  

The screen is from this kit: https://vilros.com/products/vilros-magic-mirror-v4?

I've went over the monitors menu and there is no option to turn auto scan off or any other setting that I can even think would trigger this behavior.  So I started trying to figure out a way to turn off the back light.  This command changes the brightness and seems to do what I want to do: 
`ddcutil setvcp 10 0 --display 1`  works to turn off the backlight and 
`ddcutil setvcp 10 100 --display 1` works to turn it back on. 

With that, I am attempting to modify the code to add those two commands on the setPowerDisplay function on ./components/screenLib.js.  Particularly, I am adding `ddcutil setvcp 10 100 --display 1` after line 496, and am wrapping line 498 in {} adding `ddcutil setvcp 10 0 --display 1`. This doesnt seem to work as the brightness never changes. 

Is this the right function to place it in? 

Also in troubleshooting, I have attempted to turn the screen on via ssh using the command 
`WAYLAND_DISPLAY="wayland-1" wlr-randr --output HDMI-A-1 --on`
And that doesn't turn on.  So wondering if I'm incorrect with how your code actually works. 

If you can point me in the right direction, I'd appreciate it.  Thanks! 

Setup:
Raspberry Pi 4, with most updated Raspbian
MagicMirror 2.27
`### SYSTEM:   manufacturer: ; model: ; raspberry: undefined; virtual: false
### OTHER:    timeZone: America/New_York; ELECTRON_ENABLE_GPU: undefined`

The PIR is connected to GPIO 4

Given version of OS and that they moved to Wayland, I am using Mode 10, full config:
`{
  module: 'MMM-Pir',
  position: 'top_left',
  config: {
    debug: true,
    delay: 2 * 60 * 1000,
    mode: 10,
    displayCounter: true,
    displayBar: true,
    displayStyle: "Text",
    displayLastPresence: true,
    lastPresenceTimeFormat: "LL H:mm",
    mode6_gpio: 4,
    mode6_clearGpioValue: true,
    xrandrForceRotation: "normal",
    wrandrForceRotation: "normal",
    wrandrForceMode: "1920x1080",
    touchMode: 3,
    pir_gpio: 4,
    pir_mode: 1,
  }
},`

**Comment by bugsounet** [comment]
Hi,
You can't merge ddcutil mode (8) and wlr-randr mode (10) 

So:
if `WAYLAND_DISPLAY="wayland-1" wlr-randr --output HDMI-A-1 --on` command work in terminal
I suggest to use  mode 10 (wlr-randr)

--> mode 10 is coded [there](https://github.com/bugsounet/MMM-Pir/blob/master/components/screenLib.js#L486-498)

**Comment by bugsounet** [comment]
Module updated to v2.0.0
