### ISSUE TITLE
Can't Install MMM-Pir after update to Magic Mirror 2.28.0

### ISSUE THREAD

**Issue by gonzonia** [bugsounet/MMM-Pir#81]
Updating to MagicMirror 2.280 using the @sdetweil script failed when it got to MMM-Pir. 
Trying to do a clean install of MMM-Pir on it's own results in 

`Rebuild MagicMirror...
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
Could not detect abi for version 31.1.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron

Error: Could not detect abi for version 31.1.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
    at Object.getAbi (/home/pi/MagicMirror/modules/MMM-Pir/node_modules/node-abi/index.js:39:9)
    at get ABI [as ABI] (/home/pi/MagicMirror/modules/MMM-Pir/node_modules/@electron/rebuild/lib/rebuild.js:89:39)
    at PrebuildInstall.prebuiltModuleExists (/home/pi/MagicMirror/modules/MMM-Pir/node_modules/@electron/rebuild/lib/module-type/prebuild-install.js:59:179)
    at ModuleRebuilder.prebuildInstallNativeModuleExists (/home/pi/MagicMirror/modules/MMM-Pir/node_modules/@electron/rebuild/lib/module-rebuilder.js:70:37)
    at Rebuilder.rebuildModuleAt (/home/pi/MagicMirror/modules/MMM-Pir/node_modules/@electron/rebuild/lib/rebuild.js:143:35)
    at async Rebuilder.rebuild (/home/pi/MagicMirror/modules/MMM-Pir/node_modules/@electron/rebuild/lib/rebuild.js:115:17)
    at async /home/pi/MagicMirror/modules/MMM-Pir/node_modules/@electron/rebuild/lib/cli.js:159:9
Rebuild Failed
npm error code 255
npm error path /home/pi/MagicMirror/modules/MMM-Pir
npm error command failed
npm error command sh -c installer/postinstall.sh -m `

**Comment by gonzonia** [comment]
Resolved with help from @sdetweil over at https://github.com/sdetweil/MagicMirror_scripts/issues/91 

However, had these warnings - 
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm warn deprecated npmlog@6.0.2: This package is no longer supported.
npm warn deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated are-we-there-yet@3.0.1: This package is no longer supported.
npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated gauge@4.0.4: This package is no longer supported.

**Comment by sdetweil** [comment]
the deprecated problem is nothing we can do anything about. we use a library, that uses a library  that uses a library that uses a deprecated library. 

 there may be no good mechanism to fix that except rewrite some of that not owned by us sub library code.

**Comment by bugsounet** [comment]
#63 will solve this issue,
sorry I just back home from work,
I will push it now :)
