### ISSUE TITLE
Not working after update to MagicMirror 2.28.0

### ISSUE THREAD

**Issue by Perilax-De** [bugsounet/MMM-Pir#89]
Hello,

I´m running the current version of MMM-Pir with MagicMirror 2.27.0. Everything is running fine.
After updating to MM 2.28.0 with the script of sdetweil MMM-Pir is not running anymore.
No output of the module on the Mirror and the screen isn´t going off.
Not only with the update script, also if i use git pull && npm run install-mm.

First I´m running this config:
Raspbian 11 Bullseye
mode: 1 - use vgencmd (For raspbian 10/11) with the entry dtoverlay=vc4-fkms-v3d in /boot/config.txt

for trial I changed to:
dtoverlay=vc4-kms-v3d in /boot/config.txt
and this config:
module: 'MMM-Pir',
                        position: 'right',
                        config: {
                                debug: false,
                                delay: 2 * 60 * 1000,
                                mode: 2,
                                displayCounter: true,
                                displayBar: true,
                                displayStyle: "Text",
                                displayLastPresence: true,
                                lastPresenceTimeFormat: "LL H:mm",
                                mode6_gpio: 20,
                                mode6_clearGpioValue: true,
                                xrandrForceRotation: "normal",
                                wrandrForceRotation: "normal",
                                wrandrForceMode: "1920x1080",
                                touchMode: 0,
                                pir_gpio: 22,
                                pir_mode: 1,
                                }

Before the update both options are running well, after the update no mode is working.

I tried also npm run rebuild after updating MagicMirror. 

Do you have any ideas ?

**Comment by bugsounet** [comment]
sorry for the late response, I'm very busy professionally :/

can you try this:

![image](https://github.com/user-attachments/assets/54d99b8a-28f6-4d51-bd86-34f39411f74f)

**Comment by Perilax-De** [comment]
During the day's I changed my setup. Now I'm running MM in a proxmox LXC on my server. And the Raspberry in my mirror is now only the client with Chromium in kiosk mode with a simple vcgencmd script. So the issue for me is solved. But if you want, I can test mode 9 next weekend.

**Comment by bugsounet** [comment]
pefect if solved ;)
